### ISSUE TITLE
Использование ряда компонентов приводит к ошибке 

### ISSUE THREAD

**Issue by alekmeister** [core-ds/core-components#1022]
При импорте и использовании компонентов таких как Table и Input, Modal приложение сразу крашится. Импорт в компоненте через @alfalab/core-components/table

Если поставить их отдельным пакетом, то ошибок не возникает. Импорт в компоненте через @alfalab/core-components-table

 - OS: Windows 11
 - Browser: Google Chrome

Версия пакета: @alfalab/core-components": "^43.1.1,
Сборщик: vite 4.5.0,

![alphaErr](https://github.com/core-ds/core-components/assets/102660587/f7ed8fc4-de24-4c16-976e-ba7e76e30254)

**Comment by v-gevak** [comment]
Привет! Пробовал решения [погуглить](https://www.google.com/search?q=outdated+optimize+dep+vite)? ИМХО это локальная проблема, не раз собирал приложения на vite, подобных проблем не было

**Comment by alekmeister** [comment]
> Привет! Пробовал решения [погуглить](https://www.google.com/search?q=outdated+optimize+dep+vite)? ИМХО это локальная проблема, не раз собирал приложения на vite, подобных проблем не было

Привет, да конечно, все что нашел пробовал, ничего не помогало. С другими сборщиками все было окей. Долго выяснял, что проблема локальная. Удаление package-lock.json помогло.
