### ISSUE TITLE
CalendarRange - не отображается ошибка `error` в `inputFromProps` или `inputToProps` если заполнить интервал некорректно

### ISSUE THREAD

**Issue by dmit-bar** [core-ds/core-components#1035]
# Опишите проблему

**CalendarRange** - не отображается ошибка `error` в `inputFromProps` или `inputToProps` если заполнить интервал некорректно

# Шаги для воспроизведения

1. Открыть форму с контролом `CalendarRange`, передать текст в `error` для `inputFromProps` и `inputToProps` и заполнить интервал некорректно (например 13.12.2023 и 12.12.2023)

```
inputFromProps={{
  error: 'Ошибка валидации from'
}}
inputToProps={{
  error: 'Ошибка валидации to'
}}
```

# Ожидаемое поведение

Под контролами в CalendarRange отображаются переданные ошибки `'Ошибка валидации from'` и `'Ошибка валидации to'`

**Comment by v-gevak** [comment]
Копия https://github.com/core-ds/core-components/issues/697
