### ISSUE TITLE
Error: crypto.getRandomValues() not supported в SuperEllipse

### ISSUE THREAD

**Issue by qrik116** [core-ds/core-components#1084]
# Опишите проблему
Ошибка при ssr компонента [super-ellipse](https://github.com/core-ds/core-components/blob/master/packages/icon-view/src/components/base-shape/component.tsx#L119)

<img width="699" alt="image" src="https://github.com/core-ds/core-components/assets/20581251/7dff133b-0c97-4aa4-91fa-931f873074ec">

И еще вероятнее всего, при гидрации реакт будет ругаться на разную верстку из-за уникальности значения.

# Ожидаемое поведение
Ошибок при ssr нет

# Дополнительная информация
Используется nodejs@16 версии. При использовании uuid версии 3 ошибок нет

**Comment by v-gevak** [comment]
getRandomValues используется в браузерной версии uuid. Есть понимание почему у вас нода тянет версию для браузера?

![Screenshot from 2024-02-07 13-52-46](https://github.com/core-ds/core-components/assets/40845033/bbc270ad-e1b6-4132-b645-39dff3b33938)
