### ISSUE TITLE
`CalendarMobile` крашится на длинном интервале

### ISSUE THREAD

**Issue by ekabolotina** [core-ds/core-components#1101]
# Опишите проблему
Компонент `CalendarMobile` в режиме `selectorView="month-only"` не умеет сам определять, сколько ему нужно отрисовать месяцев и падает с ошибкой, если передать в качестве выбранной даты слишком далекую дату (более 3 лет от текущего дня). 

# Шаги для воспроизведения
1. Перейти в [песочницу](https://codesandbox.io/s/core-components-calendar-range-issue-rvgzw3?file=/src/App.tsx)
2. Нажать кнопку «Open» 
3. Появляется ошибка `Cannot read properties of undefined (reading 'title')`

# Ожидаемое поведение
Открывается модальное окно с календарем.

**Comment by SiebenSieben** [comment]
@ekabolotina 

Песочница не открывается, есть возможность вернуть?

**Comment by ekabolotina** [comment]
```tsx
import { CalendarMobile } from "@alfalab/core-components/calendar/mobile";
import { useState } from "react";

export default function App() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <button type="button" onClick={() => setIsOpen(true)}>
        Open
      </button>
      <CalendarMobile
        open={isOpen}
        onClose={() => setIsOpen(false)}
        selectorView="month-only"
        selectedFrom={new Date("2020-01-01").getTime()}
      />
    </>
  );
}

```
