### ISSUE TITLE
Компонент`Typography.TitleMobile` игнорирует пропс `rowLimit`

### ISSUE THREAD

**Issue by ekabolotina** [core-ds/core-components#1132]
# Опишите проблему
Компонент`Typography.TitleMobile` игнорирует пропс `rowLimit`

# Шаги для воспроизведения
1. Отрендерить компонент
```tsx
      <Typography.TitleMobile
        tag="h4"
        view="xsmall"
        font="system"
        rowLimit={2}
      >
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam eveniet id nihil numquam officia perferendis provident quos tempora tempore, ut vel voluptates voluptatibus? Atque deserunt iusto magni nihil? Tempore.
      </Typography.TitleMobile>
```
2. Результат — текст отображается полностью
<img width="393" alt="image" src="https://github.com/core-ds/core-components/assets/8043216/ddf1a7af-8fe8-4294-aab0-81aedf9cd76b">

# Ожидаемое поведение
Отображаются только первые 2 строки текста:
<img width="393" alt="image" src="https://github.com/core-ds/core-components/assets/8043216/140fa519-52f4-4043-b238-84e7e339a868">

**Comment by Valeri8888** [comment]
привет, поставили задачу https://jira.moscow.alfaintra.net/browse/DS-4996
