### ISSUE TITLE
Доработать dev окружение для работы на windows

### ISSUE THREAD

**Issue by koretskyhub** [core-ds/core-components#117]
С недавних пор зачастую новым сотрудникам дают windows компы

Я и сам попробовал поработать с проектом на windows из под powershell, но натнулся на вот проблемные эти места
* https://github.com/core-ds/core-components/blob/master/package.json#L42
* Сеттинг переменной окружения - https://github.com/core-ds/core-components/blob/master/package.json#L40

Вероятно есть еще не одно место с такими windows-проблемками

предлагаю добавить полноценную поддержку windows в core-components!

**Comment by Lacronts** [comment]
Мы предлагаем для решения проблем с bash скриптами, сеттингом переменных и т.п установить WSL. Соответствующий пункт добавлен в README проекта.
