### ISSUE TITLE
Хватит, пожалуйста, выпускать новую мажорную версию каждую неделю!

### ISSUE THREAD

**Issue by alterfo** [core-ds/core-components#1302]
# Опишите проблему

Частые обновления версий. У нас 52 приложения и 20 библиотек. Если одна из библиотек решила обновить коры - сыпется всё у всех. А обновлять на последнюю мы вынуждены из-за одной пакостной транзитивной зависимости от которой не избавиться никак - аддон для сторибука реализующий песочницу для коров.

# Ожидаемое поведение
Стабильная мажорная версия которой можно пользоваться годами без проблем.

**Comment by SiebenSieben** [comment]
@alterfo, поставьте встречу, обсудим процесс, уже обсуждали с лидами АО/АБ
