### ISSUE TITLE
BottomSheet, после закрытия скролл контента остается заблокирован 

### ISSUE THREAD

**Issue by jkikksa** [core-ds/core-components#1325]
# Опишите проблему
При использовании пропсы `iOSLock` не выполняется код `unlockScroll` если закрывать шторку через пропсу `open`
# Шаги для воспроизведения
1) Перейти в песочницу с  Apple устройства в режиме имитации мобильного устройства https://core-ds.github.io/core-components/master/?path=/docs/sandbox--docs/code=function%20Example()%20%7B%0A%20%20%20%20const%20%5Bopen%2C%20setOpen%5D%20%3D%20React.useState(false)%3B%0A%20%20%20%20const%20handleOpen%20%3D%20()%20%3D%3E%20setOpen(true)%3B%0A%20%20%20%20const%20handleClose%20%3D%20()%20%3D%3E%20setOpen(false)%3B%0A%20%20%20%20%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CButtonMobile%20type%3D'button'%20size%3D's'%20onClick%3D%7BhandleOpen%7D%20block%3D%7Btrue%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20open%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FButtonMobile%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CBottomSheet%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20open%3D%7Bopen%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20onClose%3D%7BhandleClose%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20iOSLock%3D%7Btrue%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20initialHeight%3D'full'%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20actionButton%3D%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButtonMobile%20type%3D'button'%20size%3D's'%20onClick%3D%7BhandleClose%7D%20block%3D%7Btrue%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20close%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FButtonMobile%3E%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%3Econtent%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FBottomSheet%3E%0A%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%3B%0A%7D%0Arender(%0A%20%20%20%20%3CExample%20%2F%3E%0A)

2) Нажать кнопку Open
3) Убедиться, что для body внутри сторибуковского iframe добавлен класс `is-locked`
4) Нажать кнопку Close
5) Убедиться, что класс `is-locked` не удалился
6) Нажать кнопку Open
7) Закрыть шторку с помощью свайпа вниз
8) Убедиться, что `is-locked` удалился

# Ожидаемое поведение
После закрытия шторки скролл контента должен быть разблокирован

# Дополнительная информация
core-components 47.6.0

**Comment by renbrek** [comment]
Сделан фикс в #1434
