### ISSUE TITLE
Link: pseudo

### ISSUE THREAD

**Issue by MaksimAliakhnovich** [core-ds/core-components#148]
# Описание
Предлагаю доработать пропс pseudo.
Как сейчас: красивая картинка, но без возможности выбора через таб + проблемы с линтом.
![image](https://user-images.githubusercontent.com/33697594/178733814-fa8a8694-da5b-4607-af40-3303a8b48e20.png)

# Поведение
- По хорошему в режиме pseudo ссылка не может быть тегом `a` и должна быть `button`.  Да, сейчас можно прокинуть `Component='button'`, тогда у кнопки вылезают стили дефолтной кнопки
![image](https://user-images.githubusercontent.com/33697594/178731814-845bf206-ed70-4afc-b2b5-c40450fa8b07.png)
, которые нужно вручную убирать. Но это ладно ещё.
- Но также срабатывает алерт от линта на правило anchor-is-valid, а это уже исправить можно только отключением правила в строке. Тут видимо нужно пофиксить типы.
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/1c06306ede29bab6b0cdc1915dd6dcd6e847356b/docs/rules/anchor-is-valid.md
- и что хуже, и уже затрагивает пользователей, когда ссылка pseudo в ней обычно нет href, потому что он не надо, но тогда такой элемент не получает фокус, и его нельзя выбрать через таб. Что в принципе хотелось бы видеть для интерактивного элемента. Как и `outline`, который тут тоже не предусмотрен

**Comment by CrybabyDanChan** [comment]
[https://github.com/core-ds/core-components/pull/156](url)

**Comment by CrybabyDanChan** [comment]
#156
