### ISSUE TITLE
Modal: disableRestoreFocus

### ISSUE THREAD

**Issue by MaksimAliakhnovich** [core-ds/core-components#162]
# Опишите проблему
**Условия:** модалка внутри себя имеет контрол (у меня это Link pseudo, который не имеет фокуса, см. #148) вызова другой модалки. Для воспроизведения подойдёт любой контрол без фокуса, например Button который при открытии второй модалки получает прос loading и сохраняет его после закрытия модалки.

Пропсы для второй модалки:

**disableRestoreFocus true** - восстанавливает фокус к предыдущему активному элементу. допустим это была кнопка, которая вызвала модалку. в базовом кейсе всё работает, когда это именно кнопка с фокусом. Но в кейсе когда это Link pseudo или Button loading, см. результат в конце.

> при этом [return-focus-with-no-scroll](https://github.com/theKashey/react-focus-lock#return-focus-with-no-scroll) позволяет туда объект для отключения скрола к фокусируемому элементу, у вас нет такой возможности, допустим это потому что поддержка браузеров не очень. но это не решает проблемы

**disableRestoreFocus false** - не восстанавливает скролл, см. результат ниже.

**Результат:**
берётся первый фокусируемый элемент на странице(в моём случае предыдущей модалки) и вызывается на нём фокус, и конечно же страница скролится к нему. в моём случае этот элемент - кнопка(крест) закрытия модалки, а он в самом верху. Таким образом после закрытия второй модалки первая всегда проскролена в самый верх, это вообще не круто.

Остальные пропсы модалки для фокуса никак ситуацию не меняют, ну конечно если не отключить этот FocusLock через disableFocusLock у первой модалки. Но это не правильно.

# Ожидаемое поведение
При закрытии модалки скролл не должен скролить куда попало если фокус некуда восстановить или мы не хотим его восстанавливать.

P.S. я сомневаюсь что вы что-то с этим сделаете, такое ощущение что это проблема FocusLock при этом в их репе много похожих тем

**Comment by MaksimAliakhnovich** [comment]
а ещё disableRestoreFocus полностью ломает инпуты на мобильных устройствах. с компа всё ок, даже если эмулировать. а на мобиле все инпуты внутри модалки с этим пропсом не работают. Ставишь фокус, а он сразу снимается, даже клавиатура не успевает появиться.

**Comment by MaksimAliakhnovich** [comment]
https://codesandbox.io/s/sleepy-star-y3kx9t

предусловия:
- 2 модалки и элементы их вызова и закрытия
- контрол первой модалки на странице, контрол второй модалки в контенте первой
- контрол открытия второй модалки не может принять фокус(например это кнопка и при нажатии она переходит в статус loading)
- модалки содержат моного контента чтобы был скрол

кейсы:
1. если в модалке нет элемента с фокусом в верхней части(кнопка или крест), то она скролится до первого такого элемента, а он может быть в самом конце, как результат модалка открывается проскроленной к самому низу.
2. (в первой модалке добавить хедер с крестом или вверху контента поставить элемент с фокусом) открыть первую модалку, проскролить вниз, открыть вторую. закрыть вторую. первая модалка была проскролена вниз, а стала в начальное положение. так как контрол который вызывал вторую модалку не может принять фокус, фокус уходит на первый элемент на странице.
3. (во второй модалке есть инпут из core, самой модалке проставлен пропс disableFocusLock) открыть вторую модалку, нажать на инпут. на инпуте сразу же срабатывает onblur, инпут зависает в состоянии active и больше ни на что не реагирует. работа с инпутом невозможна. Но этот кейс решает проблему №2, т.е. если закрыть вторую модалку у первой скрол не будет менять положение.

**Comment by EGNKupava** [comment]
По первому кейсу, нужно обновить core-components до последней версии(чуть поднимали версию react-focus-lock), В твоей текущей действительно не работает адекватно disableAutoFocus.

**Comment by EGNKupava** [comment]
2. Вобще не понятно какое поведение мы ожидаем? Сфокусироваться на элементе надо, но на каком? Прошлый становиться не фокусируемым. Поэтому вроде и логично что он откатывает к первому фокусироемому. Думаю эту проблему нужно решать как-то индивидуально, со своими костылями

**Comment by EGNKupava** [comment]
3.  Отключать focusLock в child модалке плохая идея, В 1 то он остается включен. Естественно фокус пытается остаться в первой и не дает переводить на инпут. Предлогаю отключать focusLock в первой модалке по условию. Например когда блокируется кнопка, или открыта child модалка. Тут надо подумать. [в этой демке](https://codesandbox.io/s/priceless-elbakyan-wqn3u7?file=/src/App.js) работает +- адекватно. 
Мы еще обновим focusLock возможно станет лучше) Ну и как вариант мы готовы рассмотреть другие библиотеки. Если есть предложения - давай. Но пока будем докручивать что есть

**Comment by MaksimAliakhnovich** [comment]
**по кейсу 2:**
предлагать костыли делать, ну это такое...
ожидаемое поведение? странно что тут не очевидно из написанного, но надо сделать чтобы скролл работал корректно - оставался там где его оставили.

**по кейсу 3:**
тоже самое, те же костыли только в профиль.


**А по делу,** с точки зрения простого обывателя, если взять модалки из другой либы, например MUI. с тем же кодом и без всяких танцев работает предсказуемо (хотя у них там тоже есть такие пропсы, наверное та же либа используется). Скорее всего проблема в вашей реализации
