### ISSUE TITLE
Исчезающий Alert

### ISSUE THREAD

**Issue by jjswifty** [core-ds/core-components#181]
# Описание
Предлагаю добавить новый пропс компоненту Alert - autoCloseDelay, который бы позволял автоматически скрывать Alert по истечении определенного времени 

# Поведение
Поведение абсолютно идентично работе компонента Toast вместе с autoCloseDelay

**Comment by Oladii** [comment]
Не, идея использовать алерт как тост и добавлять ему несвойственные пропсы, чтобы он больше был похож на тост кажется деструктивной, скорее тосту нужно добавить кикие-то свойства.
