### ISSUE TITLE
Не работает Modal в IE

### ISSUE THREAD

**Issue by ransoq** [core-ds/core-components#211]
# Опишите проблему
При открытии модального окна возникает ошибка в IE 7-11 после обновления core до актуальной версии

# Ожидаемое поведение
При нажатии на кнопку должно появится модальное окно в IE 7-11

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
<img width="622" alt="image" src="https://user-images.githubusercontent.com/68750711/185911182-f799395a-7c9f-4081-80ec-36b15aecb3a9.png"> | ![telegram-cloud-photo-size-2-5434125544003321768-y](https://user-images.githubusercontent.com/68750711/185910394-073e1c48-6449-4da6-b200-aa19e9d0a6c6.jpg)

# Тестовый стенд

## Десктоп (если данных нет оставьте блок пустым):
 - OS: Windows
 - Browser: IE
 - Version: 7-11

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
Дополнительная информация

**Comment by ethorz** [comment]
IE 7-11 уже канули в лету, их использует очень низкий процент людей, насколько релевантно поддерживать эти версии IE? Можно на matches в своем проекте добавить поллифил отсюда https://developer.mozilla.org/ru/docs/Web/API/Element/matches

**Comment by ransoq** [comment]
У подавляющего числа сотрудников браузером по умолчанию является Internet Explorer, из-за чего отказаться от его поддержки, на текущем этапе, не представляется возможным

**Comment by jkikksa** [comment]
примерно 25% пользователей портала AlfaPeople заходят из IE11 и дропать его поддержку мы не можем

**Comment by ethorz** [comment]
Добавление каретки автоматически может брать версии, например если ^3.9.2 зависимость, где версии будут 3.*.*, что потенциально может поломать в минорных версиях. Потенциально может быть в этом причина, но самостоятельно я проверить к сожалению не могу

**Comment by SiebenSieben** [comment]
Если срочно и есть возможность — кидайте реквест.

Фиксим в IE11, более старые версии в этой библиотеке изначально не поддерживаем.

**Comment by jkikksa** [comment]
опытным путём обнаружил, что проблема в обновлении react-focus-lock c 2.5.0 до 2.9.1
```
react-focus-lock@^2.5.0:
  version "2.9.1"
```

**Comment by Lacronts** [comment]
Для того, чтобы модальные окна работали в IE, необходимо установить полифил для element matches, например вот этот https://www.npmjs.com/package/element-matches-polyfill.

**Comment by jkikksa** [comment]
проблема не в element matches, а в обновлении версии react-focus-lock до 2.9.1
Вот код, на котором падает
![image](https://user-images.githubusercontent.com/3488817/188838303-6125ceea-29bd-4fb8-990c-0038f0c41b14.png)
![image](https://user-images.githubusercontent.com/3488817/188838437-296a2447-c1c9-40ef-8c89-300b9b451e0a.png)

мы используем следующий workaround
"resolutions": {
    "react-focus-lock": "2.5.0"
},

**Comment by Lacronts** [comment]
FocusLock использует под капотом element matches(https://github.com/theKashey/focus-lock/blob/master/src/utils/tabUtils.ts#L12). Я протестировал в IE, проблем не было. Значит у вас не достает других полифилов.

**Comment by jkikksa** [comment]
а какие у тебя установленны полифилы? ) у нас используются
`react-app-polyfill/ie11` и `react-app-polyfill/stable`

кстати вот изменения в react-focus-lock https://github.com/theKashey/react-focus-lock/compare/v2.5.0...v2.9.0 после которых IE крашится, видимо тут тоже деле в какой-то зависимости глубже )

**Comment by Lacronts** [comment]
https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js

**Comment by Lacronts** [comment]
![image](https://user-images.githubusercontent.com/40845033/188876464-34a6d58d-4250-4870-aa6f-80c1201c2660.png)

**Comment by Lacronts** [comment]
![image](https://user-images.githubusercontent.com/40845033/188876707-226d93b1-7029-4248-81a0-472df25cf8c5.png)
