### ISSUE TITLE
SidePanel: элементы из `SidePanelComponent.Content` над `SidePanelComponent.Header`

### ISSUE THREAD

**Issue by vahrammer** [core-ds/core-components#254]
# Опишите проблему
Если `SidePanelComponent.Content` имеет скролл и там есть элементы с "non-static position", то они находятся над `SidePanelComponent.Header`.

<img width="706" alt="Снимок экрана 2022-09-12 в 10 14 12" src="https://user-images.githubusercontent.com/10114309/189594375-50121934-fb45-4124-9e8a-2a4312b1042d.png">

# Шаги для воспроизведения

Добавить вверху компонента `SidePanelComponent.Content` элемент с `position: relative` и проскролить.

# Ожидаемое поведение
Элементы из `SidePanelComponent.Content` не должны быть выше по Z-оси, чем `SidePanelComponent.Header`.

# Чек лист
- [ ] Фикс
- [ ] Тесты

**Comment by reabiliti** [comment]
Похожая проблема с футером тоже

<img width="555" alt="изображение" src="https://user-images.githubusercontent.com/30253042/189701457-b217acfc-3818-44ab-8651-1ca85669d24e.png">
