### ISSUE TITLE
CalendarInput не применяется значение, если присутствует ошибка

### ISSUE THREAD

**Issue by plastya-flomaster** [core-ds/core-components#276]
# Опишите проблему
Если присутствует ошибка, в мобильном виде календаря (при размере экрана <1000пикс.) нельзя выбрать заново корректное значение (отсутствует кнопка "выбрать")

В компонент не передается value, если значение невалидно 
https://github.com/core-ds/core-components/blob/master/packages/calendar-input/src/Component.tsx#L376
Т.к. наличие ошибки считает инпут невалидным https://github.com/core-ds/core-components/blob/master/packages/calendar-input/src/Component.tsx#L220

# Ожидаемое поведение
Можно применить новое корректное значение, если присутствует ошибка

Бразуер Chrome, v. 105

**Comment by reme3d2y** [comment]
Привет! А есть возможность собрать в песочнице пример в некорректным поведением? Или тут описать шаги

**Comment by plastya-flomaster** [comment]
Привет! Шаги такие:

1. Указать невалидное значение в календаре по правилам бизнес-логики (например, меньше текущей даты)
2. Сработает валидация и отобразится ошибка
3. Пользователю необходимо "поправить" ошибку, и ввести корректную дату
4. Открыть мобильный вид календаря ( экран < 1000пикс.)
5. Выбрать корректную дату в календаре
6. Не появляется кнопка "Выбрать" т.к. в календаре присутствует ошибка (пользователь только выбирает новое значение, но подтвердить его не может). развернутый календарь не закрывается
