### ISSUE TITLE
Улучшения и исправления для PureCell

### ISSUE THREAD

**Issue by NatalyaZ** [core-ds/core-components#285]
# Проблема
При использовании PureCell в веб-версии приложения были найдены некоторые недочеты. Предлагаю их исправить

## PureCell.AmountTitle
- [x] ошибка: обязательно надо указывать оба параметра minorUnits: 100, minority: 100. Исправить: сделать оба параметра необязательными
- [x] ошибка: в параметр amount попадают все свойства Amount, в том числе и класс. Исправить: объединить тип компонента с AmountProps
- [x] требование от клика: для минорной части(в целом для суммы в заголовке) надо --amount-minor-part-font-weight: 500 (https://www.figma.com/file/OiFlIdSpmFYZ5zsFGWA3TD/Web-%3A%3A-Alfa-Online-Components?node-id=43968%3A229857). Исправить: исправить css переменную в самом компоненте или добавить пропсу. _Ждет подтверждения от дизайнера_

## PureCell.Addon
- [x] дополнение: добавились значения для выравнивания по вертикали 'top' | 'center' | 'bottom'. Исправить: добавить значения
- [x] ошибка: не хватает выравнивания текста по правому краю. Исправить: добавить стили выравнивания текста

## PureCell.Text
- [x] ошибка: у части title есть отступ справа, даже если не использовать value (из-за него выравнивание при direction='vertical' не четко по центру), сохраняется span для value. Исправить: если не указан value, не добавлять отступ и не выводить теги
- [x] улучшение: при добавлении свойства word-break: break-all; текста отображается больше. Исправление: добавить свойство для обрезания текста в одну строчку

## PureCell.Category
- [x] дополнение: добавилась иконка чека (опционально withReceipt). Исправление: добавить опцию, другое вариант -- сделать отдельный компонент. _Ждет подтверждения дизайнера_
- [x] улучшение: при добавлении свойства word-break: break-all; текста отображается больше. Исправление: добавить свойство для обрезания текста в одну строчку

## PureCell.Amount
- [x] вопрос от клика: можно ли включить по дефолту view: 'withZeroMinorPart', transparentMinor: true. Решение: кажется, что никак. Не стоит указывать дефолтные значения для опциональных параметров. Но может появится идея?
- [x] ошибка: обязательно надо указывать оба параметра minorUnits: 100, minority: 100. Исправить: сделать оба параметра необязательными
- [x] ошибка: в параметр amount попадают все свойства Amount, в том числе и класс. Исправить: объединить тип компонента с AmountProps, параметр view переименовать в textView

## PureCell.Comment -> Comment
- [x] ошибка: нельзя передать строку в children. Исправление: исправить тип
- [x] дополнение: добавилось опциональное ограничение по строкам rowLimit?: 2 | 5; Исправление: добавить опцию, по-умолчанию ставить 2

**Comment by SiebenSieben** [comment]
1. PureCell.Category: добавление withReceipt будет слишком заточено под АО. Если потребуются другие иконки, то придётся плодить пропсы. Предлагаю добавить слот rightAddons, а если хотите зашить иконку на уровне компонента, то сделать обёртку в композитах.

2. PureCell.AmountTitle: уже заточен под АО (соответствующий Typography.Title). А ещё в него зашит view=withZeroMinorPart. Можно сделать его более универсальным и темизируемым через css-переменные, или забить и просто пофиксить (добавить bold=none и transparentMinor=true, тогда он будет наследовать жирность Typography.Title, которая уже 500).

3. Заметил, что у PureCell.Amount — weight, а у Amount — bold. Не уверен, что нужно фиксить, но немного смущает.

**Comment by NatalyaZ** [comment]
> Имеешь ввиду, что класснейм сейчас внутри пропса amount: AmountType ?
Да. Ну и все остальные

>Сейчас не хватает пропсы bold, как у Amount. Добавим
Если что, занимаюсь исправлениями по задаче
