### ISSUE TITLE
Проблемы с проставление класса у компонента Tab

### ISSUE THREAD

**Issue by praiz** [core-ds/core-components#328]
Указывая компоненту Tab свойство className в dom у элемента класса нет.

https://core-ds.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=render(()%20%3D%3E%20%7B%0A%20%20%20%20const%20%5BselectedSId%2C%20setSelectedSId%5D%20%3D%20React.useState(%27tab-1%27)%3B%0A%20%20%20%20const%20%5BselectedXSId%2C%20setSelectedXSId%5D%20%3D%20React.useState(%27tab-1%27)%3B%0A%20%20%20%20const%20%5BselectedXXSId%2C%20setSelectedXXSId%5D%20%3D%20React.useState(%27tab-1%27)%3B%0A%0A%20%20%20%20const%20handleSChange%20%3D%20(event%2C%20%7B%20selectedId%20%7D)%20%3D%3E%20setSelectedSId(selectedId)%3B%0A%20%20%20%20const%20handleXSChange%20%3D%20(event%2C%20%7B%20selectedId%20%7D)%20%3D%3E%20setSelectedXSId(selectedId)%3B%0A%20%20%20%20const%20handlesXXSChange%20%3D%20(event%2C%20%7B%20selectedId%20%7D)%20%3D%3E%20setSelectedXXSId(selectedId)%3B%0A%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3C%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CTabsDesktop%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20selectedId%3D%7BselectedSId%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3D%27s%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20onChange%3D%7BhandleSChange%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20view%3D%27secondary%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Aurum%27%20id%3D%27tab-1%27%20className%3D%27test%27%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Bercelium%27%20id%3D%27tab-2%27%20className%3D%27test%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Curium%27%20id%3D%27tab-3%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Neptunium%27%20id%3D%27tab-4%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Plutonuim%27%20id%3D%27tab-5%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Rubidium%27%20id%3D%27tab-6%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Californium%27%20id%3D%27tab-7%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTabsDesktop%3E%0A%20%20%20%20%20%20%20%20%3C%2F%3E%0A%20%20%20%20)%3B%0A%7D)%3B

<img width="1547" alt="Screen Shot 2022-10-26 at 15 37 25" src="https://user-images.githubusercontent.com/3061978/198028050-e3b54644-ab01-4f63-87d2-fa56b6d183eb.png">

**Comment by EGNKupava** [comment]
https://core-ds.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=render(()%20%3D%3E%20%7B%0A%20%20%20%20const%20%5BselectedSId%2C%20setSelectedSId%5D%20%3D%20React.useState(%27tab-1%27)%3B%0A%20%20%20%20const%20%5BselectedXSId%2C%20setSelectedXSId%5D%20%3D%20React.useState(%27tab-1%27)%3B%0A%20%20%20%20const%20%5BselectedXXSId%2C%20setSelectedXXSId%5D%20%3D%20React.useState(%27tab-1%27)%3B%0A%0A%20%20%20%20const%20handleSChange%20%3D%20(event%2C%20%7B%20selectedId%20%7D)%20%3D%3E%20setSelectedSId(selectedId)%3B%0A%20%20%20%20const%20handleXSChange%20%3D%20(event%2C%20%7B%20selectedId%20%7D)%20%3D%3E%20setSelectedXSId(selectedId)%3B%0A%20%20%20%20const%20handlesXXSChange%20%3D%20(event%2C%20%7B%20selectedId%20%7D)%20%3D%3E%20setSelectedXXSId(selectedId)%3B%0A%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3C%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CTabsDesktop%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20selectedId%3D%7BselectedSId%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3D%27s%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20onChange%3D%7BhandleSChange%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20view%3D%27secondary%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Aurum%27%20id%3D%27tab-1%27%20toggleClassName%3D%22plashka%22%20className%3D%27test-tab-content%27%3E%20%D0%9A%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D1%82%20%D1%82%D0%B0%D0%B1%D0%B0%3C%2FTab%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Bercelium%27%20id%3D%27tab-2%27%20className%3D%27test%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Curium%27%20id%3D%27tab-3%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Neptunium%27%20id%3D%27tab-4%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Plutonuim%27%20id%3D%27tab-5%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Rubidium%27%20id%3D%27tab-6%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CTab%20title%3D%27Californium%27%20id%3D%27tab-7%27%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FTabsDesktop%3E%0A%20%20%20%20%20%20%20%20%3C%2F%3E%0A%20%20%20%20)%3B%0A%7D)%3B

**Comment by EGNKupava** [comment]
про className применяется к контейнеру содержимого таба. А вот toggleClassName применяется к самой плашке таба
