### ISSUE TITLE
ModalResponsive при переходе breakpoint сбрасывает состояние внутри ModalResponsive.Content

### ISSUE THREAD

**Issue by Meettya** [core-ds/core-components#338]
# Опишите проблему
При переходе через breakpoint для компонента ModalResponsive состояние его содержимого сбрасывается, при использовании форм и прочего.

# Шаги для воспроизведения
1. Открыть модалку
2. выбрать чекбокс (или изменить любой активный элемент)
3. изменить размер для перехода через breakpoint

# Ожидаемое поведение
Состояние активных элементов должно сохраниться

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
**состояние чекбокса сохранено** | **состояние чекбокса сброшено**|

# Тестовый стенд

любой

# Дополнительная информация
Дополнительная информация

Видео https://disk.yandex.ru/i/Hnx-2x9khdtvEg

Пример для песочницы 

```
function Example() {
   
    const [checked, setChecked] = React.useState(false);
    const handleChange = () => setChecked(!checked);

    return (
        <Checkbox
            onChange={handleChange}
            checked={checked}
            label='Согласен с условиями'
            hint='Соглашайтесь, будьте любезны'
        />
      )
}

render(() => {
    const [open, setOpen] = React.useState(false);
    const handleModalOpen = () => setOpen(!open);
    
    return (
        <React.Fragment>
            <Button type='button' size='xs' onClick={handleModalOpen}>
                Открыть модалку
            </Button>
            <ModalResponsive open={open} onClose={handleModalOpen} size='m'>
                <ModalResponsive.Header hasCloser={true} />
                <ModalResponsive.Content>
                    <Typography.Title tag='div' view='small'>
                        Пример модалки с чекбоксом
                    </Typography.Title>
                    <br />
                    <Example />
                </ModalResponsive.Content>
                <ModalResponsive.Footer>
                    <Button view='primary' size='s' onClick={handleModalOpen}>
                        Понятно
                    </Button>
                </ModalResponsive.Footer>
            </ModalResponsive>
        </React.Fragment>
    );
});
```

**Comment by EGNKupava** [comment]
`function Example({checked, setChecked}) {
   
     const handleChange = () => setChecked(!checked);

    return (
        <Checkbox
            onChange={handleChange}
            checked={checked}
            label='Согласен с условиями'
            hint='Соглашайтесь, будьте любезны'
        />
      )
}

render(() => {
    const [open, setOpen] = React.useState(false);
    const handleModalOpen = () => setOpen(!open);
    
    const [checked, setChecked] = React.useState(false);
    
    return (
        <React.Fragment>
            <Button type='button' size='xs' onClick={handleModalOpen}>
                Открыть модалку
            </Button>
            <ModalResponsive open={open} onClose={handleModalOpen} size='m'>
                <ModalResponsive.Header hasCloser={true} />
                <ModalResponsive.Content>
                    <Typography.Title tag='div' view='small'>
                        Пример модалки с чекбоксом
                    </Typography.Title>
                    <br />
                    <Example checked={checked} setChecked={setChecked}/>
                </ModalResponsive.Content>
                <ModalResponsive.Footer>
                    <Button view='primary' size='s' onClick={handleModalOpen}>
                        Понятно
                    </Button>
                </ModalResponsive.Footer>
            </ModalResponsive>
        </React.Fragment>
    );
});`

**Comment by SiebenSieben** [comment]
https://github.com/core-ds/core-components/pull/352
