### ISSUE TITLE
Нелогичное ограничение годов в CalendarInput, если не указан проп maxDate

### ISSUE THREAD

**Issue by grewar** [core-ds/core-components#351]
# Опишите проблему
При использовании `CalendarInput`, если мы не хотим задавать ему максимальную дату `maxDate`, то при открытии модалки календаря для выбора даты, максимальный год, который там есть - это "текущий год + 1"

# Шаги для воспроизведения
1. у компонента `CalendarInput`, которому мы не указали проп `maxDate`, нажать на иконку календаря чтобы открылось модальное окно с выбором даты
2. Нажать на кнопку выбора года

# Ожидаемое поведение
Открывается список годов, в котором нет ограничения по максимальному году

# Фактическое поведение
Открывается список годов, в котором максимальный год - это "текущий год + 1"

**Comment by reme3d2y** [comment]
А какие есть случаи, когда нужно выбрать дату на несколько лет в будущем?

И сколько годов нужно показывать по дефолту? Мы ведь не будем показывать список с бесконечным скроллом

**Comment by alex-iatsenko** [comment]
> да, какой-нибудь срок действия контракта или т.п. мне кажется хватило бы нескольких десятков лет, как сделано сейчас в нижнюю сторону

можно задать пропс maxDate

**Comment by SiebenSieben** [comment]
Похожих запросов больше не было, пока закрываем
