### ISSUE TITLE
Confirmation: Выделение последний цифры

### ISSUE THREAD

**Issue by Bergotti97** [core-ds/core-components#4]
# Опишите проблему
При ошибке после ввод смс выделяется последняя цифра

# Шаги для воспроизведения
1. Неправильно ввести код от смс в `Confirmation`

# Ожидаемое поведение
Показывает ошибку, код становиться красным, placeholder на последнюю цифру
Реальный -  выделяется последняя цифра

**Comment by SiebenSieben** [comment]
Так и было задумано, можно инициировать изменение через дизайнера
