### ISSUE TITLE
в компоненте sidepanel в header при скролле карта перекрывает title

### ISSUE THREAD

**Issue by Anastasiya-Shinkovich** [core-ds/core-components#412]
#в компоненте sidepanel в header при скролле карта перекрывает title

# Шаги для воспроизведения
1. Перейти в сторибук виджетов NewclickOperationsFilters '[...](https://design/s/demo/newclick-widgets/master/?path=/story/common-newclickoperationsfilters--basic)'
2. проскролить

![Снимок экрана 2022-12-13 в 10 25 31](https://user-images.githubusercontent.com/105539708/207259740-29435b67-d592-44a5-89ec-4451e3a7e482.png)

**Comment by KnyazevSV** [comment]
Пофикшено в newclick-composite-components версии 59.0.0
