### ISSUE TITLE
Есть вероятность падения приложения использующего arui-scripts при использовании компонента Select

### ISSUE THREAD

**Issue by jkikksa** [core-ds/core-components#427]
# Опишите проблему
В компоненте Select используется компонент Scrollbar, который использует https://www.npmjs.com/package/simplebar . Если импортировать Select в версии с css-модулями  (`import { Select } from '@alfalab/core-components/select/cssm'`), то хэш начинает генерироваться в момент сборки приложения. В arui-scripts для этого используется https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/getCSSModuleLocalIdent.js который генерирует хэш в формате base64, который включает в себя символы `+` и `/`. Либа simplebar в своей работе использует querySelector https://github.com/Grsmto/simplebar/blob/master/packages/simplebar/src/simplebar.js#L181, а querySelector не допускает использования символов `+` и `/`, что может привести к падению приложения в случае если для стилей Scrollbar сгенерировался хэш содержащий запрещенные символы

**Comment by Lacronts** [comment]
ИМХО, если имя класса содержит такие символы, что к нему нельзя обратиться через querySelector, то проблема в имени класса:)
