### ISSUE TITLE
Vars: Добавить новый цвет в палитру для унификации

### ISSUE THREAD

**Issue by azinit** [core-ds/core-components#435]
# Описание
Предлагаю добавить новый цвет в палитру цветов - `#e5ecf3`

# Поведение
В мобильной теме клика есть новый цвет `#e5ecf3`, для предотвращения деунификации в кодобазе 

# Чек лист
- [ ] Тесты (не нужны)
- [ ] Документация (не нужна)

# Внешний вид

# Технические требования

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация

Сейчас (27.12.2022) в проекте клика встречается 16 появлений этого цвета (можете проверить сами), который никак не задекларирован во внутренней палитре core-components

Изменение несрочное, но зато добавило бы больше единообразия кодобазе и помогло бы избежать деунификации в будущем (когда будет много кастомных цветов не из палитры)

Используется только для тачевых компонентов/лейаутов

Как понимаю изменить надо где-то здесь, если подскажете как именно в контексте миксинов, могу и сам PR-чик закинуть 👀 
https://github.com/core-ds/core-components/blob/master/packages/themes/src/mixins/mobile.css

UPD: Со своим дизайнером (Ю.Кудрявцевой) согласовывал этот момент - действительно нужен отдельный цвет, существующие не подходят под макет проекта

**Comment by SiebenSieben** [comment]
@Oladii @O-Petrochenko

**Comment by SiebenSieben** [comment]
Очень странно, разберёмся, спасибо

Только не хардкодь)

**Comment by azinit** [comment]
Спасибо за оперативный фидбек)
За подробностями можно в личку в рабочий мессенджер

**Comment by azinit** [comment]
ping, still actual)

**Comment by Oladii** [comment]
решили с дизайнерами что этот цвет можно не заносить в токены, а оставить хардкод. В рамках перехода на BlueTint и подключение тёмной темы этот цвет тоже будет заменён на другой и, думаю, что в палитре найдётся подходящий.
