### ISSUE TITLE
React 18 > npm i > Could not resolve dependency

### ISSUE THREAD

**Issue by MaksimAliakhnovich** [core-ds/core-components#478]
# Опишите проблему
При установке @alfalab/core-components в проект с react 18 следующие зависимости требуют реакт <18:
@alfalab/icons-classic@2.3.0
@alfalab/icons-flag@2.2.0
@alfalab/icons-glyph@2.95.0
@alfalab/icons-logotype@2.19.0
react-swipeable@5.5.1
react-virtual@2.10.4

# Шаги для воспроизведения
1. npx create-next-app@latest
2. npm i @alfalab/core-components
3. npm i (для получения ошибки)

# Ожидаемое поведение
установка пакетов не выдаёт ошибки или ворнинги о несовместимости версий реакта и компонентов

# Дополнительная информация

> npm i
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @alfalab/icons-classic@2.3.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"18.2.0" from the root project
npm WARN   25 more (@alfalab/core-components, @alfalab/hooks, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.13.0 || ^17.0.1" from @alfalab/icons-classic@2.3.0
npm WARN node_modules/@alfalab/core-components/node_modules/@alfalab/icons-classic
npm WARN   @alfalab/icons-classic@"^2.3.0" from @alfalab/core-components@37.2.0
npm WARN   node_modules/@alfalab/core-components
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.13.0 || ^17.0.1" from @alfalab/icons-classic@2.3.0
npm WARN   node_modules/@alfalab/core-components/node_modules/@alfalab/icons-classic
npm WARN     @alfalab/icons-classic@"^2.3.0" from @alfalab/core-components@37.2.0
npm WARN     node_modules/@alfalab/core-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @alfalab/icons-classic@2.3.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"18.2.0" from the root project
npm WARN   10 more (@alfalab/core-components, next, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.13.0 || ^17.0.1" from @alfalab/icons-classic@2.3.0
npm WARN node_modules/@alfalab/core-components/node_modules/@alfalab/icons-classic
npm WARN   @alfalab/icons-classic@"^2.3.0" from @alfalab/core-components@37.2.0
npm WARN   node_modules/@alfalab/core-components
npm WARN
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.13.0 || ^17.0.1" from @alfalab/icons-classic@2.3.0
npm WARN   node_modules/@alfalab/core-components/node_modules/@alfalab/icons-classic
npm WARN     @alfalab/icons-classic@"^2.3.0" from @alfalab/core-components@37.2.0
npm WARN     node_modules/@alfalab/core-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @alfalab/icons-flag@2.2.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"18.2.0" from the root project
npm WARN   25 more (@alfalab/core-components, @alfalab/hooks, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.13.0 || ^17.0.1" from @alfalab/icons-flag@2.2.0
npm WARN node_modules/@alfalab/core-components/node_modules/@alfalab/icons-flag
npm WARN   @alfalab/icons-flag@"^2.2.0" from @alfalab/core-components@37.2.0
npm WARN   node_modules/@alfalab/core-components
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.13.0 || ^17.0.1" from @alfalab/icons-flag@2.2.0
npm WARN   node_modules/@alfalab/core-components/node_modules/@alfalab/icons-flag
npm WARN     @alfalab/icons-flag@"^2.2.0" from @alfalab/core-components@37.2.0
npm WARN     node_modules/@alfalab/core-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @alfalab/icons-flag@2.2.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"18.2.0" from the root project
npm WARN   10 more (@alfalab/core-components, next, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.13.0 || ^17.0.1" from @alfalab/icons-flag@2.2.0
npm WARN node_modules/@alfalab/core-components/node_modules/@alfalab/icons-flag
npm WARN   @alfalab/icons-flag@"^2.2.0" from @alfalab/core-components@37.2.0
npm WARN   node_modules/@alfalab/core-components
npm WARN
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.13.0 || ^17.0.1" from @alfalab/icons-flag@2.2.0
npm WARN   node_modules/@alfalab/core-components/node_modules/@alfalab/icons-flag
npm WARN     @alfalab/icons-flag@"^2.2.0" from @alfalab/core-components@37.2.0
npm WARN     node_modules/@alfalab/core-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @alfalab/icons-glyph@2.95.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"18.2.0" from the root project
npm WARN   25 more (@alfalab/core-components, @alfalab/hooks, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.13.0 || ^17.0.1" from @alfalab/icons-glyph@2.95.0
npm WARN node_modules/@alfalab/core-components/node_modules/@alfalab/icons-glyph
npm WARN   @alfalab/icons-glyph@"^2.89.0" from @alfalab/core-components@37.2.0
npm WARN   node_modules/@alfalab/core-components
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.13.0 || ^17.0.1" from @alfalab/icons-glyph@2.95.0
npm WARN   node_modules/@alfalab/core-components/node_modules/@alfalab/icons-glyph
npm WARN     @alfalab/icons-glyph@"^2.89.0" from @alfalab/core-components@37.2.0
npm WARN     node_modules/@alfalab/core-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @alfalab/icons-glyph@2.95.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"18.2.0" from the root project
npm WARN   10 more (@alfalab/core-components, next, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.13.0 || ^17.0.1" from @alfalab/icons-glyph@2.95.0
npm WARN node_modules/@alfalab/core-components/node_modules/@alfalab/icons-glyph
npm WARN   @alfalab/icons-glyph@"^2.89.0" from @alfalab/core-components@37.2.0
npm WARN   node_modules/@alfalab/core-components
npm WARN
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.13.0 || ^17.0.1" from @alfalab/icons-glyph@2.95.0
npm WARN   node_modules/@alfalab/core-components/node_modules/@alfalab/icons-glyph
npm WARN     @alfalab/icons-glyph@"^2.89.0" from @alfalab/core-components@37.2.0
npm WARN     node_modules/@alfalab/core-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @alfalab/icons-logotype@2.19.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"18.2.0" from the root project
npm WARN   25 more (@alfalab/core-components, @alfalab/hooks, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.13.0 || ^17.0.1" from @alfalab/icons-logotype@2.19.0
npm WARN node_modules/@alfalab/core-components/node_modules/@alfalab/icons-logotype
npm WARN   @alfalab/icons-logotype@"^2.19.0" from @alfalab/core-components@37.2.0
npm WARN   node_modules/@alfalab/core-components
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.13.0 || ^17.0.1" from @alfalab/icons-logotype@2.19.0
npm WARN   node_modules/@alfalab/core-components/node_modules/@alfalab/icons-logotype
npm WARN     @alfalab/icons-logotype@"^2.19.0" from @alfalab/core-components@37.2.0
npm WARN     node_modules/@alfalab/core-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @alfalab/icons-logotype@2.19.0
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"18.2.0" from the root project
npm WARN   10 more (@alfalab/core-components, next, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.13.0 || ^17.0.1" from @alfalab/icons-logotype@2.19.0
npm WARN node_modules/@alfalab/core-components/node_modules/@alfalab/icons-logotype
npm WARN   @alfalab/icons-logotype@"^2.19.0" from @alfalab/core-components@37.2.0
npm WARN   node_modules/@alfalab/core-components
npm WARN
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^16.13.0 || ^17.0.1" from @alfalab/icons-logotype@2.19.0
npm WARN   node_modules/@alfalab/core-components/node_modules/@alfalab/icons-logotype
npm WARN     @alfalab/icons-logotype@"^2.19.0" from @alfalab/core-components@37.2.0
npm WARN     node_modules/@alfalab/core-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-swipeable@5.5.1
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"18.2.0" from the root project
npm WARN   25 more (@alfalab/core-components, @alfalab/hooks, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.0.0-0" from react-swipeable@5.5.1
npm WARN node_modules/@alfalab/core-components/node_modules/react-swipeable
npm WARN   react-swipeable@"^5.5.1" from @alfalab/core-components@37.2.0
npm WARN   node_modules/@alfalab/core-components
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.0.0-0" from react-swipeable@5.5.1
npm WARN   node_modules/@alfalab/core-components/node_modules/react-swipeable
npm WARN     react-swipeable@"^5.5.1" from @alfalab/core-components@37.2.0
npm WARN     node_modules/@alfalab/core-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-virtual@2.10.4
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"18.2.0" from the root project
npm WARN   25 more (@alfalab/core-components, @alfalab/hooks, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm WARN node_modules/@alfalab/core-components/node_modules/react-virtual
npm WARN   react-virtual@"^2.3.2" from @alfalab/core-components@37.2.0
npm WARN   node_modules/@alfalab/core-components
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm WARN   node_modules/@alfalab/core-components/node_modules/react-virtual
npm WARN     react-virtual@"^2.3.2" from @alfalab/core-components@37.2.0
npm WARN     node_modules/@alfalab/core-components

**Comment by Lacronts** [comment]
Обновили все пакеты, кроме react-virtual. На текущий момент 2.10.4 последняя версия
