### ISSUE TITLE
В компоненте CardImage не отображается карта

### ISSUE THREAD

**Issue by DronVol** [core-ds/core-components#480]
Добрый день!

Наткнулся на плавающую проблему. В компоненте CardImage может не срабатывать стиль loaded даже при том, что карта картинка сама по себе загрузилась и компонент отрендерился. Пока что получилось решить только добавлением внешнего стиля, который добавляет opacity картинке и убирает background обёртки, но это видится мне костылём.

Воспроизводится:
arui-scripts: 13.2.0
react: 16.14.0
core-components: 37.2.0
Chrome: 109.0.5414.87
Mac OS

<CardImage
    className={ cn('cardImageLoaded') }
    cardId={ cardId }
    width={ 366 }
/>
<img width="2048" alt="Снимок экрана 2023-01-23 в 22 11 21" src="https://user-images.githubusercontent.com/10686374/214128757-60480262-8040-4dce-8dba-d229e79009eb.png">

<img width="2048" alt="Снимок экрана 2023-01-23 в 22 11 00" src="https://user-images.githubusercontent.com/10686374/214128768-b8f24466-0dff-4c38-977e-8929571775bd.png">

Подскажите, в чём может быть проблема?

**Comment by Lacronts** [comment]
Выставил ПР, опубликовал бетку 38.0.0-beta.0. Будет возможность проверить?
