### ISSUE TITLE
Мобильная Side Panel отходит от верха вьюпорта

### ISSUE THREAD

**Issue by dokudryavtsev** [core-ds/core-components#485]
# Опишите проблему
Если резко сделать скролл верх у мобильной SidePanel, то появляется отступ сверху.
Критикал баг для нашей команды, так как из-за этого отступа начинает трясти весь виджет при использовании Яндекс карты.

# Шаги для воспроизведения
1. Открыть SidePanel на мобильном устройстве
2. Cделать быстрый скролл вниз и обратно вверх

# Ожидаемое поведение
Отступ не должен появляться 

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
<img width="479" alt="image" src="https://user-images.githubusercontent.com/123724248/215039179-ab2e36ff-f472-4663-a256-c69920192d22.png"> | <img width="486" alt="image" src="https://user-images.githubusercontent.com/123724248/215038978-70fda129-19c2-49f7-8248-6f779051a20a.png">

# Тестовый стенд

## Смартфон (если данных нет оставьте блок пустым):
 - Device: Samsung, любой android девайс
 - OS: Android 12+
 - Browser: Chrome

# Дополнительная информация
Дополнительная информация
Приложил видео в рокете Core-Components

**Comment by Lacronts** [comment]
Это баг мобильного хрома. Воспроизводится, если sticky контент вложен в fixed контейнер

**Comment by Lacronts** [comment]
Это баг мобильного хрома. Воспроизводится, если sticky контент вложен в fixed контейнер
