### ISSUE TITLE
Ошибки при рендере компонента Modal в тестах react-test-renderer

### ISSUE THREAD

**Issue by DronVol** [core-ds/core-components#489]
При рендере компонента Modal в тестовой среде react-test-renderer происходят следующие ошибки

Error: Uncaught [TypeError: mql.removeEventListener is not a function]
FocusLock: could not obtain ref to internal node
Error: Uncaught [TypeError: _reactDom.default.findDOMNode is not a function]

arui-scripts: 13.2.0
react: 16.14.0
core-components: 37.2.0
Chrome: 109.0.5414.87
typescript: 4.7.4
react-test-renderer: 16.9.0
Mac OS

Частично проблема решается обновлением FocusLock до версии 2.9.2
https://github.com/theKashey/react-focus-lock/issues/123

**Comment by Lacronts** [comment]
react-focus-lock обновим.

mql.removeEventListener is not a function - это мокать надо - https://stackoverflow.com/questions/39830580/jest-test-fails-typeerror-window-matchmedia-is-not-a-function

Почему findDOMNode is not a function надо локально разбираться
