### ISSUE TITLE
Неудобно скроллить табы (Tabs)

### ISSUE THREAD

**Issue by ekabolotina** [core-ds/core-components#50]
Компонент [Tabs](https://digital.alfabank.ru/s/core-components/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-tabs--tabs) устроен таким образом, что если табы не помещаются в область видимости, то появляется возможность [скроллить их внутри контейнера](https://digital.alfabank.ru/s/core-components/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-tabs--tabs#%D1%82%D0%B0%D0%B1%D1%8B-%D1%81%D0%BE-%D1%81%D0%BA%D1%80%D0%BE%D0%BB%D0%BB%D0%BE%D0%BC).

Для красоты полоса прокрутки скрыта, поэтому пользователь может прокручивать табы только с помощью жестов (на трекпаде или сенсорном экране) либо с помощью колесика мыши при зажатой клавише shift. Это очень неудобно, к тому же совсем неочевидно, что эти табы можно скроллить.

Я бы предложил добавить кнопки, которые должны появляться автоматически, если есть возможность скроллить табы. Нажатие на кнопку будет прокручивать контейнер на несколько табов вперед или назад. За эталон можно взять [MUI Tabs](https://mui.com/material-ui/react-tabs/#automatic-scroll-buttons).

**Comment by SiebenSieben** [comment]
Для десктопа висит реквест с другим решением:
https://github.com/core-ds/core-components/pull/336

А для мобилки, как я понимаю, ничего и не требуется менять.
