### ISSUE TITLE
Предлагаю внутри Steps добавить поддержку рендера под мобилу, планшет и десктоп

### ISSUE THREAD

**Issue by bwn-z** [core-ds/core-components#506]
# Описание
[Компонент Steps](https://core-ds.github.io/core-components/master/?path=/docs/steps--steps)
есть свойство `isVerticalAlign: boolean`, предлагаю, что можно было передавать как 
`isVerticalAlign={false}` или `isVerticalAlign={{ mobile: false, tablet: { s: false, m: false, l: true}, desktop: true}}`

# Поведение
В зависимости от экрана клиента будет рендериться либо вертикально, либо горизонтально. Для большинства наших клиентов подходит десктоп, но мы делаем адаптивную верстку. Сейчас нам придется использовать useMedia хук, чтобы понимать экран клиента и рендерить в нужном виде: на маленьких экран рендерить Steps - горизонтально, на больших - вертикально

# Чек лист

# Внешний вид
Без изменений

# Технические требования
Поддержка клиентских размеров экранов. По аналогии, как у нас с колонками `<Grid.Col width={{ mobile: {s:..., m:..., l:...}, desktop: ...}} order={{ mobile:..., desktop:..., tablet:...}} /> `

**Comment by Oladii** [comment]
Обсудим с дизайнерами разделение на десктопный и мобильный компонент. Предположение что вертикальные шаги могут превратиться в горизонтальные и наоборот при адаптиве довольно спорное.

**Comment by bwn-z** [comment]
> Обсудим с дизайнерами разделение на десктопный и мобильный компонент. Предположение что вертикальные шаги могут превратиться в горизонтальные и наоборот при адаптиве довольно спорное.

Странно, но в НИБе сейчас так используют, плюс мы прошли дизайн-чек и выкатились с костылем самописным
