### ISSUE TITLE
Возможность задать свою маску в phone-input

### ISSUE THREAD

**Issue by khidirbekov** [core-ds/core-components#544]
# Описание
Предлагаю добавить возможность задавать маску в компоненту phone-input

# Поведение
Инпут phone-input работает с маской, которую задали через внешний проп

# Чек лист

# Внешний вид

# Технические требования

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
Сейчас в  компонента phone-input задана маска "+7 XXX XXX-XX-XX",  хотелось бы, чтобы была возможность задавать свою маску, чтобы формат был например такого вида: "+7(XXX)XXX-XX-XX"

**Comment by agapovx** [comment]
+1 за данное расширение функционала. Ибо бывают случаи на проектах АБ, когда нужна по разным причинам ( например, для обратной совместимости с второй частью приложения и сервисами бэка ) именно другая маска, отличная от текущей.

**Comment by Lacronts** [comment]
Вся внутренняя логика phone-input строится вокруг дефолтной маски, если ее менять, то нет никакого смысла использовать этот компонент. Для кастомных масок лучше использовать MaskedInput
