### ISSUE TITLE
NumberInput. Не работают пропсы `fractionLength` и `separator`

### ISSUE THREAD

**Issue by jkikksa** [core-ds/core-components#552]
# Опишите проблему
Пропсы `fractionLength` и `separator` не оказывают никакого влияния на отображение значения внутри инпута.

# Шаги для воспроизведения
![image](https://user-images.githubusercontent.com/3488817/220663305-a158d3b8-8ff1-4db6-9379-f358835a1ea9.png)

https://core-ds.github.io/core-components/master/?path=/docs/sandbox--page/code=function%20Example()%20%7B%0A%20%20%20%20const%20%5Bvalue%2C%20setValue%5D%20%3D%20React.useState(1.55555)%3B%0A%20%20%20%20%0A%20%20%20%20const%20handleChange%20%3D%20(e%2C%20%7B%20value%20%7D)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20setValue(value)%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CNumberInput%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20value%3D%7Bvalue%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20block%3D%7Btrue%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20onChange%3D%7BhandleChange%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20label%3D%27Label%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20separator%3D%27%2C%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fractionLength%3D%7B%202%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3D%27m%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%3B%0A%7D%0Arender(%0A%20%20%20%20%3CExample%20%2F%3E%0A)

# Ожидаемое поведение
Пропсы `fractionLength` и `separator` должны оказывать влияние на отображение значения внутри инпута.

**Comment by Valeri8888** [comment]
@jkikksa Привет, чтобы работали пропсы необходимо изменять состояние через valueString и передавать валидное значение в стейт

**Comment by jkikksa** [comment]
а зачем тогда вообще нужен value в колбеке? всё равно приходится всё время работать со строкой )

**Comment by Valeri8888** [comment]
чтобы была возможность получить числовое представление значения инпута при необходимости
