### ISSUE TITLE
Select: ошибка onBlur

### ISSUE THREAD

**Issue by aaartyukhov** [core-ds/core-components#608]
# Опишите проблему
После клика на сам чекбокс, событие onBlur не срабатывает

# Шаги для воспроизведения
1. Открыть выпадающий список
2. Выбрать или снять чекбокс (именно чекбокс, не подпись к нему) 
3. Снять фокус, событие onBlur  не отрабатывает

**Comment by Lacronts** [comment]
Можешь в песочнице это воспроизвести?
