### ISSUE TITLE
CalendarRange - при ручном вводе правой границы даты меньше левой в `payload` не приходит значение даты `dateTo`

### ISSUE THREAD

**Issue by dmit-bar** [core-ds/core-components#638]
# Опишите проблему

**CalendarRange** - при ручном вводе правой границы даты меньше левой в `payload` не приходит значение даты `dateTo`, поэтому нет возможности провалидировать и заблокировать форму.

# Шаги для воспроизведения

1. Открыть форму с контролом `CalendarRange`, ввести вручную даты "от" и "до" (дату "до" ввести меньше "от")

# Ожидаемое поведение

В `payload.dateTo` придет значение которое можно было бы провалидировать и отобразить ошибку пользователю

# Дополнительная информация

![CalendarRange_dateTo](https://user-images.githubusercontent.com/95961125/233611755-60bb5d63-60c8-4d2b-9dbf-76319c574e28.png)

**Comment by SiebenSieben** [comment]
PDS-1578

**Comment by Lacronts** [comment]
https://github.com/core-ds/core-components/pull/665
