### ISSUE TITLE
Select - неявное поведение пропа preventFlip

### ISSUE THREAD

**Issue by dmit-bar** [core-ds/core-components#640]
# Опишите проблему

**Select** - неявное поведение пропа `preventFlip`. Ожидается что при `preventFlip == undefined` компонент будет расценивать это как `preventFlip == false`.

# Шаги для воспроизведения

1. Перейти на страницу с Select
2. Раскрыть длинный список уходящий за нижний край экрана

# Ожидаемое поведение

При нехватке места список отобразиться сверху контрола по умолчанию (без передачи пропа `preventFlip={false}`)

**Comment by Lacronts** [comment]
Текущее поведение было согласовано между дизайнерам банка. Решили оставить как есть
