### ISSUE TITLE
PhoneInput - невозможно ввести номер +77 (Казахстан)

### ISSUE THREAD

**Issue by overcomzi** [core-ds/core-components#650]
# Опишите проблему
В поле Мобильный телефон (PhoneInput) невозможно ввести номера, которые начинаются на +7 7 (Казахстан)
К примеру, номер +7 (705) 224 00 93
![image](https://user-images.githubusercontent.com/48058556/234551008-a9662359-721c-4ab4-abd3-720a65aa8aaa.png)

# Шаги для воспроизведения

# Ожидаемое поведение

# Чек лист

# Внешний вид

# Тестовый стенд

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
Дополнительная информация

**Comment by Lacronts** [comment]
![Screenshot from 2023-04-26 23-07-39](https://user-images.githubusercontent.com/40845033/234635776-468d85cd-aac7-4a96-9fa1-a3f961c77ea4.png)
