### ISSUE TITLE
Tab - не устанавливается значение dataTestId

### ISSUE THREAD

**Issue by Atcad** [core-ds/core-components#651]
# Опишите проблему
При установке на компонент Tab свойства dataTestId значение свойства не устанавливается в разметке

# Шаги для воспроизведения
1. Перейти на страницу '...'
2. Нажать на кнопку '...'

# Ожидаемое поведение
При нажатии на кнопку должно появится модальное окно

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
** Ожидаемый  ** | ** Фактический    **|

# Тестовый стенд

## Десктоп (если данных нет оставьте блок пустым):
 - OS: MacOS
 - Browser: Safari
 - Version: 10

## Смартфон (если данных нет оставьте блок пустым):
 - Device: iPhone 6
 - OS: iOS 10
 - Browser: Chrome
 - Version: 65

# Дополнительная информация
Дополнительная информация

**Comment by Lacronts** [comment]
Устанавливается так - 
![photo_2023-04-26_23-04-00](https://user-images.githubusercontent.com/40845033/234634725-7cfe4dda-4893-4b8e-956e-2abab395e1d3.jpg)

**Comment by Atcad** [comment]
Для клика по табам ориентируемся на id таба? в таком случае на secandary табе его не хватает

**Comment by Lacronts** [comment]
Добавили dataTestId на кнопку таба [#659](https://github.com/core-ds/core-components/pull/659)
