### ISSUE TITLE
Skeleton для элементов Tab

### ISSUE THREAD

**Issue by Atcad** [core-ds/core-components#662]
# Описание
Предлагаю добавить скелетон для каждого из элементов Tab в нутри TabList
На данный момент такой возможности нет

# Поведение
При загрузке страницы табы отображаются отдельно в состоянии Skeleton

# Внешний вид
<img width="1264" alt="image" src="https://github.com/core-ds/core-components/assets/48721141/c29f48ad-296d-4e51-81f9-5b4c5b383fc5">

**Comment by Oladii** [comment]
Пока не понятно назначение такого состояния. Получается мы знаем что на странице есть табы, но не знаем их контент и количество, я думаю в таком кейсе скелетон экрана долен иметь более общий вид и собираться из обычных скелетонов. Но в любом случае будем обсуждать с дизайнерами скелетонизацию компонентов.
