### ISSUE TITLE
Ошибка сборки при обновлении на версию 41.9.0 

### ISSUE THREAD

**Issue by sivan2203** [core-ds/core-components#695]
После обновления на версию 41.9.0 при попытке сборки возникает ошибка: 
![Screenshot 2023-05-30 at 21 48 40](https://github.com/core-ds/core-components/assets/51863540/062393a1-2b80-40c0-8603-c715a48b1894)
Удалял node-modules и package-lock.json устанавливал заново все зависимости, но проблема не уходит.

# Шаги для воспроизведения
1. Обновиться на версию 41.9.0
2. Запустить сборку проекта

**Comment by Lacronts** [comment]
Насколько я понял, вы пытаетесь импортировать @alfalab/core-components/vars/index.css внутри scss файла. В индексном файле у нас лежат postcss миксины, не нужно рытаться их обрабатываться с помощью sass-loader. Почему бы не подключить наши переменные через обычный css файл? 

```
import './vars.css'; // Должен импортировать @alfalab/core-components/vars/index.css
import './project-styles.scss';

```
