### ISSUE TITLE
Не описан пропс disabled для компонента Tooltip

### ISSUE THREAD

**Issue by gadzhimari** [core-ds/core-components#737]
# Опишите проблему
В API компонента тултипа не описано поле disabled. Например, ситуация когда чипсы задизейблены, но при этом тултип все равно отображается.

**Comment by Valeri8888** [comment]
Привет!
Опиши, пожалуйста, подробнее логику кт ты подразумеваешь для поля disabled

**Comment by gadzhimari** [comment]
Допустим у нас есть радио-группа с тэгами и при наведении на тэг должен отображаться тултип. Так вот, если не передать в тултип пропс `disabled`, то радио-группа не дизейблится, даже если я явно передал для компонента Tag пропс disabled.

```
<RadioGroup
    direction="horizontal"
    type="tag"
    name="person"
    value={ person }
>
        <Tooltip
            // eslint-disable-next-line @typescript-eslint/ban-ts-comment
            // @ts-ignore
            disabled={ true }
            position="top"
            trigger="hover"
            fallbackPlacements={ ['top'] }
            content="Нельзя оформить более одной страховки на клиента"
        >
            <Tag disabled={ true }>{ currentPerson }</Tag>
        </Tooltip>
</RadioGroup>
```

Соответственно пропс `disabled` не описан у компонента Tooltip.

**Comment by Valeri8888** [comment]
Можешь собрать пример в песочнице? 
вот мой [пример](https://core-ds.github.io/core-components/master/?path=/docs/sandbox--docs/code=function%20Example()%20%7B%0A%20%20%20%20const%20%5Bvalue%2C%20setValue%5D%20%3D%20React.useState('one')%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3CRadioGroup%0A%20%20%20%20%20%20%20%20%20%20%20%20direction%3D%22horizontal%22%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3D%22tag%22%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3D%22person%22%0A%20%20%20%20%20%20%20%20%20%20%20%20value%3D%7B%20value%20%7D%0A%3E%0A%20%20%20%20%20%20%20%20%3CTooltip%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3D%22top%22%0A%20%20%20%20%20%20%20%20%20%20%20%20trigger%3D%22hover%22%0A%20%20%20%20%20%20%20%20%20%20%20%20fallbackPlacements%3D%7B%20%5B'top'%5D%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20content%3D%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20true%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3F%20'%D0%9D%D0%B5%D0%BB%D1%8C%D0%B7%D1%8F%20%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%82%D1%8C%20%D0%B1%D0%BE%D0%BB%D0%B5%D0%B5%20%D0%BE%D0%B4%D0%BD%D0%BE%D0%B9%20%D1%81%D1%82%D1%80%D0%B0%D1%85%D0%BE%D0%B2%D0%BA%D0%B8%20%D0%BD%D0%B0%20%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0'%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3A%20'%D0%9C%D0%BE%D0%B6%D0%BD%D0%BE%20%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%82%D1%8C%20%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE%20%D0%BD%D0%B0%20%D0%B4%D1%80%D1%83%D0%B3%D0%BE%D0%B5%20%D0%BB%D0%B8%D1%86%D0%BE'%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CTag%20value%3D'one'%20disabled%3D%7B%20true%20%7D%3E'currentPerson'%20%3C%2FTag%3E%0A%20%20%20%20%20%20%20%20%3C%2FTooltip%3E%0A%3C%2FRadioGroup%3E%0A%20%20%20%20)%3B%0A%7D%0Arender(%0A%20%20%20%20%3CExample%20%2F%3E%0A)) и в нем тег дизейблится

**Comment by Lacronts** [comment]
Не должно быть у тултипа пропа disabled. Если так нужно, то можешь сделать controlled версию тултипа или явно передать open={false}
