### ISSUE TITLE
Добавить токены для кастомизации Button

### ISSUE THREAD

**Issue by ekabolotina** [core-ds/core-components#762]
# Описание
Предлагаю добавить несколько новых токенов для кастомизации компонента [Button](https://core-ds.github.io/core-components/master/?path=/docs/components-button--docs).

# Поведение
Нужны следующие токены:
- отступы слева и справа (`padding-left`, `padding-right`) для разных размеров кнопок
- размер шрифта для разных размеров кнопок.

**Comment by Valeri8888** [comment]
@Oladii

**Comment by SiebenSieben** [comment]
Есть пример в макетах? На данный момент такая кастомизация в дизайн-системе не допускается

**Comment by ekabolotina** [comment]
Это не банковский продукт, но используются Core Components. Там чуть другие размеры, не такие гигантские, как по дефолту. Сейчас приходится таким способом переопределять, а хотелось бы по-нормальному. Через токены можно поменять высоту кнопок, но при этом нельзя поменять размер шрифта и отступы, что странно.

<img width="635" alt="image" src="https://github.com/core-ds/core-components/assets/8043216/9181afae-acba-4f31-a970-3d941e34cba8">

**Comment by SiebenSieben** [comment]
В кор-компоненты добавляем кастомизацию, которая имеет смысл с точки зрения дизайн-системы, отступы и размер текста сейчас прибиты, ишью пока закрываю
