### ISSUE TITLE
Компонент `Button` задает внешние отступы

### ISSUE THREAD

**Issue by ekabolotina** [core-ds/core-components#769]
# Опишите проблему
Очень часто нужно задать кастомный отступ у кнопки, навесив на нее `className`. При этом компонент `Button` [задает внешние отступы](https://github.com/core-ds/core-components/blob/master/packages/button/src/index.module.css#L26). Получается, что для того, чтобы задать внешние отступы, нужно перебивать стили библиотеки. Либо оборачивать кнопку в какой-то ненужный `div`.

# Ожидаемое поведение
Компонент не должен задавать внешние отступы, т.к. это выходит за рамки его ответственности.

**Comment by Lacronts** [comment]
Проблема в том, что html button, который используется в компоненте в некоторых браузерах имеет дефолтный margin, собственно поэтому мы его и вынуждены обнулять.

**Comment by Lacronts** [comment]
В 14 сафари, например, мобильном

**Comment by ekabolotina** [comment]
Я думаю, что это плохое решение. Для сброса стилей надо использовать `reset.css`. А компонент не должен управлять внешними отступами, тем более такой базовый, как кнопка.

**Comment by SiebenSieben** [comment]
В либе изначально заложен такой подход и сейчас менять его не представляется возможным. По такой логике надо и у Title убрать марджин, но это взорвёт все приложения)

**Comment by ekabolotina** [comment]
> В либе изначально заложен такой подход и сейчас менять его не представляется возможным. По такой логике надо и у Title убрать марджин, но это взорвёт все приложения)

Не очень конструктивный подход.

В чем проблема сделать `reset.css`, в нем прописать `button { margin: 0 }` и подключить его в самом верху `default.css`?

**Comment by ekabolotina** [comment]
> По такой логике надо и у Title убрать марджин, но это взорвёт все приложения)

Насколько мне известно, у Title есть пропс `defaultMargins={false}`, который позволяет отключить ваши кастомные отступы.
