### ISSUE TITLE
Дергается экран айфона при заполнении confirmation

### ISSUE THREAD

**Issue by Rusflipz** [core-ds/core-components#770]
# Опишите проблему
При вводе в поле confirmation на айфоне дергается экран

# Шаги для воспроизведения
1. Заполните полностью анкету
2. Нажать на 5 шаге кнопку  отправить, ввести в поле любые цифры (на айфоне)

# Ожидаемое поведение
Экран не дергается

# Внешний вид
https://github.com/core-ds/core-components/assets/87382883/fb6e480f-4e2d-4cef-89d1-4627f82ec72c

# Тестовый стенд
https://testjmb.alfabank.ru/cc-short/step1

## Смартфон (если данных нет оставьте блок пустым):
 - Device: iPhone 8-13
 - OS: последний возможный
 - Browser: Chrome, Safari

# Дополнительная информация
Блок с подтверждением находится внутри модалки
 (проблема из-за того, что за модалкой есть контент с высотой больше 100vh, и в айфонах position: fixed не помогает избавиться от возможности скролла, от этого и баг

**Comment by Lacronts** [comment]
Не думаю, что чем-то вам можем помочь. При открытии модалки на body вешается overflow: hidden, что должно блокировать скролл контента за модалкой, но в вашем случае это не работает. 


Могу лишь предложить вариант с transitionProps. В момент открытия модального окна вызывается коллбэк transitionProps.onEnter, тут можете самостоятельно заблокировать скролл в вашем контейнере, а в момент закрытия модального окна скролл восстановить

```
<Modal 
    transotionProps={{
        onEnter: () => // блокируете скролл
        onExited: () => // восстанавливаете скролл в контейнере
    }}
```
