### ISSUE TITLE
Проблема при использовании библиотеки совместно с ViteJS

### ISSUE THREAD

**Issue by sivan2203** [core-ds/core-components#804]
При использовании ViteJS в dev режиме проект собирается нормально, если попытаться сделать продакшн сборку то возникает ошибка "Uncaught ReferenceError: require is not defined". 

<img width="542" alt="Screenshot 2023-08-22 at 13 32 18" src="https://github.com/core-ds/core-components/assets/51863540/d171fbfd-ab41-437c-9100-57978cea1cfb">
<img width="422" alt="Screenshot 2023-08-22 at 13 32 45" src="https://github.com/core-ds/core-components/assets/51863540/a5d1f2a1-4c4e-4f0a-b27f-8bb7c75280c8">

Происходит это из-за того что после сборки в файлах билда остаются куски кода содержащие функции require(). Vite поддерживает только модули ES6, соответственно вместо require нужно использовать import.

Мы пытались решить эту проблему принудительной сборкой пакета "core-components" (и остальных сопутствующих ему пакетов с иконками и тд.) в синтаксисе commonJS используя плагин https://github.com/originjs/vite-plugins/tree/main/packages/vite-plugin-commonjs, который был взят из обсуждения подобной темы тут https://github.com/vitejs/vite/issues/3409. Проблему это не решило, в файлах билда все равно остается код в старом синтаксисе. Сталкивались ли вы с такими проблемами?

Прилагаю скрин с конфигом Vite.

<img width="1136" alt="Screenshot 2023-08-22 at 13 41 21" src="https://github.com/core-ds/core-components/assets/51863540/5e6ee29a-585e-4892-94cd-c1178bf432f8">

**Comment by Lacronts** [comment]
Нужно добавить в конфиг -     
```
build: {
        commonjsOptions: {
            transformMixedEsModules: true
        }
    }
```

**Comment by sivan2203** [comment]
Отлично, работает. Большое спасибо!
