### ISSUE TITLE
Ошибка сборки компонента таблицы trow

### ISSUE THREAD

**Issue by krovorgen** [core-ds/core-components#84]
# Опишите проблему
В своей сборке использую компонент таблицы trow, но в css файлах есть вложенность, из-за чего сборка крашится, в других компонентах такое не наблюдается.

# Шаги для воспроизведения
В готовом пакете перейти в файл стилей компонента trow. Проблемный участок кода
`
.table__withoutBorder_hjusi {
    td {
        border: none;
    }
}
`

# Ожидаемое поведение
Без вложенностей

**Comment by reme3d2y** [comment]
Привет! Кинь плз линк на приложение\ветку

**Comment by SiebenSieben** [comment]
Посмотрел как сейчас, вложенности нет. Вероятно, уже неактуально.
