### ISSUE TITLE
Предлагаю для SelectDesktop и SelectWithTags добавить пропс availableHeight для Popover

### ISSUE THREAD

**Issue by graffad** [core-ds/core-components#847]
# Описание
Есть компонент BaseSelect , в котором для Popover можно добавить возможность прокинуть пропс автоматического определения высоты когда не хватает места сверху или снизу. [popover в селекте](https://github.com/core-ds/core-components/blob/791bb79388b6844c90bd5f58265863fabb2689c2/packages/select/src/components/base-select/Component.tsx#L525)

# Ожидаемое поведение
Popover в селектах подстраивает свою высоту под границы экрана

**Comment by SiebenSieben** [comment]
Просьба приложить ссылку на макет
