### ISSUE TITLE
Сломались типы для Select

### ISSUE THREAD

**Issue by khidirbekov** [core-ds/core-components#908]
# Опишите проблему
После обновления core-components с 41.19.0 до последней версии 42.11.0 сломались типы Select.
Т.е. если раньше мы импортировали
```typescript
import type { OptionShape } from '@alfalab/core-components/select';
```
то теперь нужно добавлять typings в конце
```typescript
import type { OptionShape } from '@alfalab/core-components/select/typings';
```
Так не только для OptionShape но и для других типов из @alfalab/core-components/select

# Шаги для воспроизведения
1. Обновить core-components до последней версии
2. Попробовать импортировать тип из @alfalab/core-components/select

# Ожидаемое поведение
При импорте из @alfalab/core-components/select находится необходимый тип

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
** Ожидаемый  ** | ** Фактический    **|

# Тестовый стенд

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
Дополнительная информация

**Comment by Lacronts** [comment]
Это сделано намеренно. Во всех компонентах, где есть мобильный, десктопный и респонсивный компонент общие типы, утилиты и прочее должны импортироваться из @alfalab/core-components/{component}/shared
