### ISSUE TITLE
Добавился проп в InputAutocomplete без брекин ченжей

### ISSUE THREAD

**Issue by khidirbekov** [core-ds/core-components#909]
# Опишите проблему
После обновления core-components с 41.19.0 до 42.20.0 в  InputAutocomplete стало требовать прокинуть проп `onFilter` в обязательном порядке. Просмотрел список ченжей, но нигде не заметил про это изменение.

Порой когда обновляешь версию библиотеки подобные ченжи проскакивают и это расстривает, потому что на поиски проблемы уходит много времени. Хотелось бы заранее видеть их в списке breaking changes

# Шаги для воспроизведения

# Ожидаемое поведение

# Чек лист

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
** Ожидаемый  ** | ** Фактический    **|

# Тестовый стенд

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация

**Comment by Lacronts** [comment]
В 42 версии InputAutocomplete стал называться InputAutocompleteDesktop. В CHANGELOG об этом написано, хотя стоило написать более подробно.

```md
- Десктопный компонент теперь экспортируется из desktop -> import {InputAutocompleteDesktop} from '@alfalab/core-components/input-autocomplete/desktop'
```
