### ISSUE TITLE
Ошибка при открытии Select

### ISSUE THREAD

**Issue by vvikota** [core-ds/core-components#917]
При открытии компонента Select в консоле выпадает ошибка

![image](https://github.com/core-ds/core-components/assets/30027067/8b755170-8d79-46df-b92b-3a33bc1ed3d4)

**Comment by Lacronts** [comment]
Мы не можем отказаться от инлайн стилей внутри селекта. Проблему нужно решать на вашей стороне, например, добавлением "style-src 'self' 'unsafe-inline';" в CSP
