### ISSUE TITLE
Генерация координат для комопонентов Circle, NoShape, Rectangle и SuperElipse

### ISSUE THREAD

**Issue by malmo-east** [core-ds/core-components#932]
# Описание
Я хочу добавить новые размеры для IconView компонента, заметил что в файле path.ts, дочерних компонентов Circle, NoShape, Rectangle и SuperElipse есть фиксированные данные координат. Как вы их генерируйте, к примеру для нового значения 240x240px

**Comment by Oladii** [comment]
это так не работает, новые размеры добавляются только после согласования с дизайн-лидами продуктов.
