### ISSUE TITLE
Ошибка Cannot read property '0' of undefined  at ResizeObserver.<anonymous>

### ISSUE THREAD

**Issue by MaximRhz** [core-ds/core-components#964]
# Опишите проблему
На версии core-components 39.3.0, появляется ошибка  Uncaught TypeError: Cannot read property '0' of undefined
 at ResizeObserver.<anonymous> (var n = e[0].contentBoxSize[0].inlineSize;)

![image](https://github.com/core-ds/core-components/assets/25844915/f026d17a-acd4-4bf5-a714-e72a371dbbae)
 
 Выяснил, что ошибка появляется в функции:

```
   const handleElementsResize = (entries: ResizeObserverEntry[]) => {
            if (Array.isArray(entries[0].contentBoxSize)) {
                const [{ inlineSize }] = entries[0].contentBoxSize;

                collapseElements(inlineSize);
            } else {
                // old browser compatibility. See https://caniuse.com/mdn-api_resizeobserverentry_contentboxsize
                collapseElements(entries[0].contentRect.width);
            }
        };
 ```

Строка : const [{ inlineSize }] = entries[0].contentBoxSize;
Файл: use-collapsible-elements.ts

# Ожидаемое поведение
Не должно быть ошибки

## Десктоп:
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79

**Comment by Lacronts** [comment]
Это исправлено в 42.12.0.
