### ISSUE TITLE
Инишиал значение для Input под управлением react-hook-form

### ISSUE THREAD

**Issue by viachaslau-latushkin** [core-ds/core-components#980]
# Опишите проблему
При использовании defaultValues react-hook-form
const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({ **defaultValues: formDefaultValues** });

вместе с Input и регистрации его
<Input {...register(ИМЯ ИНПУТА)} />

![Снимок экрана 2023-11-16 в 15 09 08](https://github.com/core-ds/core-components/assets/16937593/612ecc7e-e904-4127-a0ec-22d3da4f6a37)

Value атрибут тэга Input пустой
А после клика по интпуту или на фокус - значение пропадает навсегда

# Шаги для воспроизведения
1. Самая свежая версия react-hook-form
2. Версия библиотеки 43.1.0

# Ожидаемое поведение
Корректная работа с какой-нибудь библиотекой для создания форм
Например react-hook-form

**Comment by v-gevak** [comment]
https://github.com/core-ds/core-components/issues/989#issuecomment-1822808873

**Comment by viachaslau-latushkin** [comment]
https://react-hook-form.com/get-started#IntegratingControlledInputs
